### ISSUE TITLE
Training variables missing from feature importance plots

### ISSUE THREAD

**Issue by kramerto** [HEP-KBFI/ml-training#22]
Some input variables do not show up in the feature importance plots. Which ones seems sort of random (although potentially rather low ranked variables) and it also differs between Even_train_Odd_test and Odd_train_Even_test which ones are missing.

**Comment by acarvalh** [comment]
If you ask for low max number of trees, low iterations and have too much
variables this can happen. It generally means that the variable is so
unimportant that it was not even used. You can also try increase the number
of iterations or decrease the learning rate.

However, If high ranked variables differ appearing in even/ odd it is a
pretty good indication that you don’t have statistics to make a reliable
training.
If they are low ranked in one and not appearing in other... those are just
to be removed, it is an statistical fluctuation. BTW there is no need for
making even and odd training for pruning variables differently, to prune
variables it suffice use all stats, and them with a “final” list do a
even/odd.

Tobias Kramer <notifications@github.com> escreveu em ter, 7/07/2020 às
13:46 :
