### ISSUE TITLE
Implementation of reweighting procedure for nonRes training.

### ISSUE THREAD

**Issue by tolange** [HEP-KBFI/ml-training#26]
In nonRes the different signal scenarios are not given by different samples but by reweighting the sum of all nonRes samples for the scenario of interest. This needs to be implemented for the ml/training as well copying and reweighting the signal samples reading weight from the training NTuples.

**Comment by tolange** [comment]
first implementation done. After the info/folder structure is finalized and the plotting is fixed we can close this issue.

**Comment by Laurits7** [comment]
Closing.
