### ISSUE TITLE
Refactoring of the mass fitting/decorelation from hh_aux tools into a separate script 

### ISSUE THREAD

**Issue by tolange** [HEP-KBFI/ml-training#28]
Creation of a separate script for the gen_mHH vs. input var profiling. The idea is to use this script prior to the pso hyper parameter search and final training script.

**Comment by rdewanje** [comment]
Any special reason why do we do that ? hh_aux_tools.py file was created to hold functions like these.

**Comment by tolange** [comment]
Yes, currently we have to create the TProfiles for the mass decorelation either ourselves and fit them ourselves or we have to use the final training script until it fails and then copy them to the desired location. Also the final training script while creating new fits is loading the ones in the declared file location which is rather confusing and  not as handy as having a dedicated script to do exactly that. Ideally PSO and the training script then just load the fits created by this dedicated script.

**Comment by Laurits7** [comment]
gen_mHH_profiling.py is now included in the 'master' branch. Closing issue.
