### ISSUE TITLE
Restructure of the per channel info folder

### ISSUE THREAD

**Issue by tolange** [HEP-KBFI/ml-training#30]
With regard to the nonRes training it can be useful to have separate files for training variables and loaded samples. 
Since some files like the tau_ID_training/apllication containing the file path to the training samples and the expected BG yields in the SR will be shared between the nonRes case and the Res case, it would make sense to have one folder per channel with two subfolders for the Res and nonRes training.

**Comment by rdewanje** [comment]
I am in favor of this as well. We use "info/HH/<channel>/Resonant" and "info/HH/<channel>/NonResonant" directory nomenclature where the common stuff goes into "info/HH/<channel>/" and the NonRes/Res specific stuff go into the respective sub-directories.

**Comment by Laurits7** [comment]
Resolved. Closing.
