### ISSUE TITLE
Change of keys.txt to accommodate per era sample loading

### ISSUE THREAD

**Issue by tolange** [HEP-KBFI/ml-training#31]
Since in some eras not all signal samples are available it might be useful to have a per era definition of the samples we load for training. We could restructure it into a dict containing the sample keys and the eras for which to load them.

I.e  something like this: 

[
{'key': 'ZZ', 'eras': [16,17,18]},
...
....
{'key': 'signal_ggf_nonresonant_node_sm_4v', 'eras': [17,18]}
]

**Comment by Laurits7** [comment]
Implemented. Merged to master & Closing.
